### ISSUE TITLE
Setup troubles / no profile output

### ISSUE THREAD

**Issue by stackptr** [lucapinello/create_artisan_alarms_phidget#1]
After `pip install SR700_Artisan_Profile_Builder` and running `SR700_Artisan_Profile_Builder` I get the following:

<img width="1212" alt="screen shot 2019-02-18 at 3 22 06 pm" src="https://user-images.githubusercontent.com/4542907/52980857-0776a000-3391-11e9-8be3-db56630df422.png">

I also get the following traceback:

```
SR700 Artisan Profile Builder - Luca Pinello 2019 (@lucapinello)


Send bugs, suggestions or *green coffee* to lucapinello AT gmail DOT com


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5.py", line 519, in _draw_idle
    self.draw()
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_agg.py", line 437, in draw
    self.figure.draw(self.renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1493, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2635, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axis.py", line 1204, in draw
    self.label.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/text.py", line 706, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/text.py", line 305, in _get_layout
    clean_line, ismath = self.is_math_text(line, self.get_usetex())
  File "/usr/local/lib/python2.7/site-packages/matplotlib/text.py", line 1188, in is_math_text
    if cbook.is_math_text(s):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 2035, in is_math_text
    "matplotlib display text must have all code points < 128 or use "
ValueError: matplotlib display text must have all code points < 128 or use Unicode strings
```

I think there is some missing setup instructions here or otherwise some unfulfilled dependencies. If I create a new graph and leave everything default, I get the instructions but the x-axis label is off:

<img width="1212" alt="screen shot 2019-02-18 at 3 27 40 pm" src="https://user-images.githubusercontent.com/4542907/52980975-bfa44880-3391-11e9-8dfe-7990793bf62c.png">

Trying to use this software as directed by the video I encounter a few problems:
- The temperature curve generated is only shown if I press the button to create a new graph
- There is no saved file `artisan_profile_alarms.alrm` that I can find in the directory I've run the script
- `target_curve_for_artisan_profile_alarms.alrm.pdf` that is generated cannot be opened in Preview.app or any other reader.

This is, I think, the relevant Traceback generated when the program crashes after setting the fan curve:

```
The points selected are:

[(108.87976539589442, 452.3191094619666), (241.9002932551319, 264.47124304267163), (447.83577712609963, 365.49165120593693), (690.2287390029325, 422.2634508348794), (807.4838709677418, 449.8144712430427)]
The points selected are:

[(148.2932551319648, 9.01669758812616), (270.475073313783, 7.996289424860854), (482.3225806451612, 6.011131725417441), (690.2287390029325, 4.063079777365492), (811.4252199413488, 2.0408163265306127)]
Traceback (most recent call last):
  File "/usr/local/bin/SR700_Artisan_Profile_Builder", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/SR700_Artisan_Profile_Builder/__init__.py", line 323, in main
    plt.savefig(pdf_filename)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 695, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 2062, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_qt5agg.py", line 94, in print_figure
    super(FigureCanvasQTAgg, self).print_figure(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/backend_pdf.py", line 2586, in print_pdf
    self.figure.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/figure.py", line 1493, in draw
    renderer, self, artists, self.suppressComposite)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axes/_base.py", line 2635, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/image.py", line 141, in _draw_list_compositing_images
    a.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/axis.py", line 1204, in draw
    self.label.draw(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/artist.py", line 55, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/text.py", line 706, in draw
    bbox, info, descent = textobj._get_layout(renderer)
  File "/usr/local/lib/python2.7/site-packages/matplotlib/text.py", line 305, in _get_layout
    clean_line, ismath = self.is_math_text(line, self.get_usetex())
  File "/usr/local/lib/python2.7/site-packages/matplotlib/text.py", line 1188, in is_math_text
    if cbook.is_math_text(s):
  File "/usr/local/lib/python2.7/site-packages/matplotlib/cbook/__init__.py", line 2035, in is_math_text
    "matplotlib display text must have all code points < 128 or use "
ValueError: matplotlib display text must have all code points < 128 or use Unicode strings
```

**Comment by lucapinello** [comment]
This may be related to the matplotlib version you are using, I have version
2.2.3.

Can you try the following:

pip install matplotlib==2.2.3


Thanks,


Luca

**Comment by stackptr** [comment]
Just gives me some output that the requirement is already satisfied:

```
❯ pip install matplotlib==2.2.3
Requirement already satisfied: matplotlib==2.2.3 in /usr/local/lib/python2.7/site-packages (2.2.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (2.3.1)
Requirement already satisfied: backports.functools-lru-cache in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (1.5)
Requirement already satisfied: subprocess32 in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (3.5.3)
Requirement already satisfied: pytz in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (2018.9)
Requirement already satisfied: six>=1.10 in /usr/local/Cellar/protobuf/3.6.1.3_1/libexec/lib/python2.7/site-packages (from matplotlib==2.2.3) (1.11.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (2.8.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (1.0.1)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (0.10.0)
Requirement already satisfied: numpy>=1.7.1 in /usr/local/lib/python2.7/site-packages (from matplotlib==2.2.3) (1.16.1)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/site-packages (from kiwisolver>=1.0.1->matplotlib==2.2.3) (40.6.3)
```

Same issues when running it afterward

**Comment by lucapinello** [comment]
I see that you are using the Python provided  with OSX.

Try to install Anaconda Python, I tested with that. This may solve your
problem.

**Comment by clarsen** [comment]
It works for me with `pyenv` python version 3.6.5 and can use pipenv and local install to get it running...
```
brew install pyenv
pyenv install 3.6.5
pipenv --python ~/.pyenv/shims/python3
pipenv install -e .
```
